'use server';
/**
 * @fileOverview A Genkit flow for analyzing weekly sales data for wholesalers.
 *
 * - analyzeWeeklySalesTrend - A function that handles the analysis of weekly sales data.
 * - WeeklySalesDataInput - The input type for the analyzeWeeklySalesTrend function.
 * - SalesAnalysisOutput - The return type for the analyzeWeeklySalesTrend function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Input Schema
const WeeklySalesRecordSchema = z.object({
  productId: z.string().describe('Unique identifier for the product.'),
  productName: z.string().describe('Name of the product.'),
  quantitySold: z.number().int().positive().describe('Total quantity of the product sold.'),
  revenue: z.number().positive().describe('Total revenue generated by the product.'),
  saleDate: z.string().datetime().describe('Date and time of the sale in ISO 8601 format.'),
});

const WeeklySalesDataInputSchema = z.object({
  salesRecords: z.array(WeeklySalesRecordSchema).describe('A list of individual sales records for the week.'),
  weekStartDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe('The start date of the sales week in YYYY-MM-DD format.'),
  weekEndDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe('The end date of the sales week in YYYY-MM-DD format.'),
});
export type WeeklySalesDataInput = z.infer<typeof WeeklySalesDataInputSchema>;

// Output Schema
const TopPerformingProductSchema = z.object({
  productId: z.string().describe('Unique identifier for the top-performing product.'),
  productName: z.string().describe('Name of the top-performing product.'),
  totalQuantitySold: z.number().int().positive().describe('Total quantity of this product sold during the week.'),
  totalRevenue: z.number().positive().describe('Total revenue generated by this product during the week.'),
  reason: z.string().describe('A brief explanation of why this product is considered top-performing.'),
});

const SalesAnalysisOutputSchema = z.object({
  summary: z.string().describe('An AI-generated overall summary of the weekly sales performance.'),
  topPerformingProducts: z.array(TopPerformingProductSchema).describe('A list of products that performed exceptionally well during the week.'),
  emergingTrends: z.array(z.string()).describe('A list of emerging sales trends observed in the weekly data (e.g., increased sales in a specific product category, or products showing unusual growth).'),
  anomalies: z.array(z.string()).describe('A list of anomalies or unusual sales patterns detected (e.g., unexpected drops in sales for popular items, or sudden spikes).'),
});
export type SalesAnalysisOutput = z.infer<typeof SalesAnalysisOutputSchema>;

// Wrapper function
export async function analyzeWeeklySalesTrend(input: WeeklySalesDataInput): Promise<SalesAnalysisOutput> {
  return wholesalerSalesTrendAnalysisFlow(input);
}

// Prompt definition
const salesTrendAnalysisPrompt = ai.definePrompt({
  name: 'wholesalerSalesTrendAnalysisPrompt',
  input: { schema: WeeklySalesDataInputSchema },
  output: { schema: SalesAnalysisOutputSchema },
  prompt: `You are an expert sales analyst for a wholesale frozen food distributor.\nYour task is to analyze the provided weekly sales data and generate a concise summary, identify top-performing products, emerging trends, and any notable anomalies.\n\nThe sales data covers the week from {{{weekStartDate}}} to {{{weekEndDate}}}.\n\nHere is the raw sales data:\n{{#if salesRecords}}\n  {{#each salesRecords}}\n    - Product ID: {{this.productId}}, Name: {{this.productName}}, Quantity Sold: {{this.quantitySold}}, Revenue: {{this.revenue}}, Sale Date: {{this.saleDate}}\n  {{/each}}\n{{else}}\n  No sales records provided for this week.\n{{/if}}\n\nBased on the provided sales records:\n1.  **Generate a comprehensive summary** of the week's sales performance. Highlight overall revenue, total units sold, and general observations.\n2.  **Identify and list the top-performing products**. For each, provide its ID, name, total quantity sold, total revenue, and a brief reason why it's considered top-performing (e.g., highest revenue, highest volume, significant increase from previous implied performance, etc.).\n3.  **Point out any emerging trends**. These could be products gaining popularity, specific sales patterns, or changes in customer purchasing behavior during this week. Consider if certain product types are selling particularly well.\n4.  **Highlight any anomalies**. These are unexpected events like significant drops in sales for usually popular products, unusual spikes, or any data points that stand out as irregular.\n\nEnsure your output adheres strictly to the provided JSON schema for SalesAnalysisOutput.\n`,
});

// Flow definition
const wholesalerSalesTrendAnalysisFlow = ai.defineFlow(
  {
    name: 'wholesalerSalesTrendAnalysisFlow',
    inputSchema: WeeklySalesDataInputSchema,
    outputSchema: SalesAnalysisOutputSchema,
  },
  async (input) => {
    const { output } = await salesTrendAnalysisPrompt(input);
    return output!;
  }
);
